
services:
    vllm-openai:
        env_file:
        - path: ./.env
          required: true # default
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./models:/models
        # environment:
        #     - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
        ports:
            - 8000:8000
        ipc: host
        image: vllm/vllm-openai:latest
        command: --model ${MODEL} --trust-remote-code
